### ISSUE TITLE
vue3.2.25 TypeError: Cannot read properties of undefined (reading 'header')

### ISSUE THREAD

**Issue by seanhepps** [SortableJS/vue.draggable.next#129]
vue.draggable.next version is 4.1.0
vue version is 3.2.25
ERROR INFO:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'header')
    at getSlot (vuedraggable.js:59:24)
    at computeChildrenAndOffsets (vuedraggable.js:65:18)
    at Proxy.render (vuedraggable.js:166:54)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5030:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5156:9)
    at mountComponent (runtime-core.esm-bundler.js:4939:9)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)

**Comment by bianpratama** [comment]
@seanhepps 

Do make sure that you have version `4.1.0` of `vuedraggable`. I also missed that because I did `yarn add vuedraggable`, and installed version `2.24.3` for Vue 2 instead.

**Comment by chendi-forward** [comment]
@seanhepps delete  node_modules and clean npm

**Comment by andradei** [comment]
@bianpratama Your solution works.

**Comment by alessandroAmedei** [comment]
I am using Vite and i solved doing:
`import Draggable from 'vuedraggable/src/vuedraggable';`
instead of
`import Draggable from 'vuedraggable';`

**Comment by jlazaro135** [comment]
> @seanhepps delete node_modules and clean npm

hey, thanks!! works for me 😃
