### ISSUE TITLE
Error using vue3.2.32 + vite 2.9.4

### ISSUE THREAD

**Issue by muyi0728** [SortableJS/vue.draggable.next#138]
![企业微信截图_9f0d6be8-e024-44d8-86ca-f0d626918c3b](https://user-images.githubusercontent.com/23134854/163355810-1dc246a1-c096-4055-829c-a9aae2120950.png)

**Comment by muyi0728** [comment]
When I fixed the version of vue to 3.2.31 and the version of vite to 2.9.1, the code can run normally without error

**Comment by Tnze** [comment]
same here

**Comment by lhermann** [comment]
Made some tests.
The issue is not vite. It works fine with vite@2.9.5 (latest as of the time of this writing)
The problem is with **vue@3.2.32 and higher**

**Comment by chobitsnerv** [comment]
Similiar here:
`Uncaught TypeError: Cannot set properties of null (setting '__draggable_context')
    at addContext2 (componentStructure.js:3:15)
    at componentStructure.js:33:7
    at Array.forEach (<anonymous>)
    at ComponentStructure.updated (componentStructure.js:32:18)
    at Proxy.mounted (vuedraggable.js:125:24)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2685:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at render2 (runtime-core.esm-bundler.js:5688:9)`
I did a test and it works again after I removed the  tag="transition-group"
Tested under  "vue": "^3.2.33", "vite": "^2.9.5"

**Comment by chobitsnerv** [comment]
https://github.com/vuejs/core/blob/main/CHANGELOG.md#3232-2022-04-12
**vue@3.2.32**looks update "transition-group" which may casue some issues here, I have some warning msg as following from chrome.
Hope it can help in some degree.

![image](https://user-images.githubusercontent.com/18134025/163710827-c8322a3c-1e18-45e1-aa65-dfdda5bd12e2.png)
@David-Desmaisons

**Comment by sortingbubbles** [comment]
We are having the same issue after updating to vue 3.2.33.

**Comment by pungfen** [comment]
I having same issue after updating to vue 3.2.33

**Comment by muyi0728** [comment]
In the temporary solution of vue3.2.33 version, remove the tag="transition-group" attribute, you can run the code normally

**Comment by ddmy** [comment]
#### vue@3.233
 `Uncaught (in promise) TypeError: Cannot set properties of null (setting '__draggable_context')`
remove the tag="transition-group" attribute, it's ok

**Comment by JokerMartini** [comment]
If you remove the transition-group attribute, then you are forced to use a vertical layout of draggable. What does transition group do under the hood that i could mimic without adding the attribute?

**Comment by JokerMartini** [comment]
Code like this
```
<draggable
      v-model="appItems"
      tag="transition-group"
      v-bind="dragOptions"
      item-key="uid"
    >
      <template #item="{ element }">
        <AppItemCard :item="element" :key="element.uid" />
      </template>
    </draggable>
```
Which previously worked, no longer works with the latest version of vue.

**Comment by JokerMartini** [comment]
if you downgrade your vue to vue 3.2.30 it will work

**Comment by superchangme** [comment]
> if you downgrade your vue to vue 3.2.30 it will work

Have you solved it?

**Comment by superchangme** [comment]
it's none of business with vite, it's problem about vue's component `transition-group` ,it lost el dom property

**Comment by dpschen** [comment]
This is the same error as in this issue: https://github.com/SortableJS/vue.draggable.next/issues/140#issuecomment-1123622724=

There is a pull request with a fix that is also available as forked package:
[zhyswan-vuedraggable](https://github.com/zhyswan/vue.draggable.next)

**Comment by jomanning** [comment]
> This is the same error as in this issue: [#140 (comment)](https://github.com/SortableJS/vue.draggable.next/issues/140#issuecomment-1123622724)
> 
> There is a pull request with a fix that is also available as forked package: [zhyswan-vuedraggable](https://github.com/zhyswan/vue.draggable.next)

This was able to fix it for me, thank you
