### ISSUE TITLE
transition does not work

### ISSUE THREAD

**Issue by murilolivorato** [SortableJS/vue.draggable.next#228]
Hello , I am using vue Draggable with VUE 3 .
but transition is not workig .

I did many ways , I did like this -

```
  <Draggable
                                              v-model="data"
                                              class="space-y-3"
                                              drag-class="drag"
                                              ghost-class="ghost"
                                              group="listproperties"
                                              item-key="index"
                                              tag="ul"
                                              handle=".handle"
                                              @start="drag = true"
                                              @end="drag = false"
                                            >

                                              <template #item="{element}">
                                                <TransitionGroup type="transition" :name="!drag ? 'flip-list' : null" tag="div">
                                                  <my-component
                                                                         :property="element"
                                                                         :index="data.indexOf(element)"
                                                                         :key="data.indexOf(element)" >
                                                </TransitionGroup>
                                              </template>
                                            </Draggable>

```

CSS -

```
.flip-list-move {
  transition: transform 0.5s;
}

.no-move {
  transition: transform 0s;
}

.ghost {
  opacity: 0.5;
  background: #c8ebfb;
}

.list-group {
  min-height: 20px;
}

.list-group-item {
  cursor: move;
}

.list-group-item i {
  cursor: pointer;
}

```

**Comment by WailanTirajoh** [comment]
Yap, tried with the example provided, got error on console.

**Comment by alecgibson** [comment]
We're also getting a console error:

```
logger.ts:114 TypeError: Cannot set properties of null (setting '__draggable_context')
    at addContext (vuedraggable.umd.js:4478:1)
    at eval (vuedraggable.umd.js:4523:1)
    at Array.forEach (<anonymous>)
    at ComponentStructure.updated (vuedraggable.umd.js:4522:1)
    at Proxy.mounted (vuedraggable.umd.js:4808:1)
    at eval (vue.esm-bundler.js:4690:1)
    at callWithErrorHandling (vue.esm-bundler.js:1640:1)
    at callWithAsyncErrorHandling (vue.esm-bundler.js:1648:1)
    at hook.__weh.hook.__weh (vue.esm-bundler.js:4670:1)
    at flushPostFlushCbs (vue.esm-bundler.js:1807:1)
```

**Comment by thibaultvanc** [comment]
same error here on vue3

**Comment by MiladRST** [comment]
Using transition causes a console error !

**Comment by Kamsou** [comment]
Hey guys ! is there a fix?

**Comment by jTiKey** [comment]
The only available transition is 
```
const dragOptions = {
  animation: 200,
}
```
`draggable(v-bind="dragOptions"`

**Comment by Filip1139** [comment]
same problem here

**Comment by fuxianwei** [comment]
+1

**Comment by ronannnn** [comment]
+1

**Comment by hahatulk** [comment]
+1

**Comment by john-psina** [comment]
+1

**Comment by vukadinFE** [comment]
+ 1

**Comment by vukadinFE** [comment]
> The only available transition is
> 
> ```
> const dragOptions = {
>   animation: 200,
> }
> ```
> 
> `draggable(v-bind="dragOptions"`

For anyone who is searching for the answer, if you put only `:animation="200"` or what ever duration you need, without setting the tag to `transition-group` or adding extra `<TransitionGroup>` it will just work.

**Comment by eric-gitta-moore** [comment]
> > The only available transition is
> > ```
> > const dragOptions = {
> >   animation: 200,
> > }
> > ```
> > 
> > 
> >     
> >   
> > `draggable(v-bind="dragOptions"`
> 
> For anyone who is searching for the answer, if you put only `:animation="200"` or what ever duration you need, without setting the tag to `transition-group` or adding extra `<TransitionGroup>` it will just work.

yes!  By understanding the source code, I saw that $attrs will be directly passed to the option data of the sortable

```js
  watch: {
    $attrs: {
      handler(newOptionValue) {
        const { _sortable } = this;
        if (!_sortable) return;
        getValidSortableEntries(newOptionValue).forEach(([key, value]) => {
          _sortable.option(key, value);
        });
      },
      deep: true
    }
  },
```
