### ISSUE TITLE
Cannot read properties of undefined (reading 'element')

### ISSUE THREAD

**Issue by SupertigerDev** [SortableJS/vue.draggable.next#87]
Hey, I dont know what im doing wrong but i'm getting this error on vue compat build 3.2.11 with vuedraggable 4.1.0
```vue
<template>
  <Draggable v-model="items" item-key="name">
    <template #item="{element, index}">
      {{ index }}
      {{ element }}
    </template>
  </Draggable>
</template>

<script lang="ts">
import Draggable from "vuedraggable";
import { defineComponent } from "vue";
export default defineComponent({
  components: { Draggable },
  data() {
    return {
      items: [{ name: "owo" }]
    };
  }
});
</script>
```

```
TypeError: Cannot read properties of undefined (reading 'element')
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist/index.js?!./src/components/HeaderTabs.vue?vue&type=template&id=4a346f4a&scoped=true:17:26)
    at renderFnWithContext (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:2482:21)
    at Object.get (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:8325:24)
    at computeNodes (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:4601:21)
    at computeComponentStructure (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:4646:15)
    at Proxy.render (webpack-internal:///./node_modules/vuedraggable/dist/vuedraggable.umd.js:4767:32)
    at Proxy.compatRender (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:8132:27)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:2529:44)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:7050:34)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/compat/dist/vue.runtime.esm-bundler.js:634:29)
```

**Comment by SupertigerDev** [comment]
Fixed it, I just had to do
```js
Vue.configureCompat({ COMPONENT_V_MODEL: false });
```

**Comment by rendomnet** [comment]
@supertiger1234 I have same error and 'Vue.configureCompat({ COMPONENT_V_MODEL: false });' is not fixing it.

**Comment by Guziq** [comment]
Try

```
configureCompat({
    COMPONENT_V_MODEL: false,
    RENDER_FUNCTION: false
})
```

@rendomnet

**Comment by Anders3byg** [comment]
Im getting this as well i dont have vue/compat installed, so is this the needed fix still, and where would i implement it?
